version: '3.1'
services:
    bankA:
        container_name: "bankA"
        image: nginx:alpine
        volumes:
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./src:/var/www/html"
        ports:
            - "127.10.0.10:80:80"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: nginx -g 'daemon off;'
        restart: always

        depends_on:
            - php
            - mysqldb
    bankB:
        container_name: "bankB"
        image: nginx:alpine
        volumes:
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./src:/var/www/html"
        ports:
            - "127.10.0.11:80:80"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: nginx -g 'daemon off;'
        restart: always
        depends_on:
            - php
            - mysqldb
    bankC:
        container_name: "bankC"
        image: nginx:alpine
        volumes:
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./src:/var/www/html"
        ports:
            - "127.10.0.12:80:80"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: nginx -g 'daemon off;'
        restart: always
        depends_on:
            - php
            - mysqldb
    php:
        container_name: "php_bank"
        build: ./docker/php
        image: php
        restart: always
        working_dir: /var/www/html
        user: root
        #command: chown root /var/www/html
        volumes:
            - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./src:/var/www/html"
    mysqldb:
        container_name: "db_bank"
        image: "mysql:5.7"
        volumes:
           - ./docker/mysql:/var/lib/mysql
           - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
        ports:
            - "${DB_PORT}:3306"
        environment:
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
